apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: example
  template:
    metadata:
      labels:
        app: prometheus
        purpose: example
      annotations:
          ad.datadoghq.com/prometheus.check_names: '["openmetrics"]'
          ad.datadoghq.com/prometheus.init_configs: '[{}]'
          ad.datadoghq.com/prometheus.instances: |
            [
              {
                "prometheus_url": "http://%%host%%:%%port%%/metrics",
                "namespace": "single",
                "metrics": [
                  {"promhttp_metric_handler_requests_total": "prometheus.handler.requests.total"},
                  "go*",
                  "prometheus_tsdb*"
                ],
                "exclude_metrics": [
                  "go_info",
                  "prometheus_tsdb_size_retentions_total"
                ]
              }
            ]
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
          - containerPort: 9090

---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-service
spec:
  selector:
    app: prometheus
    purpose: example
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090